[package]
name = "toumei"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.4.0"
digest = "0.10.7"
rayon = "1.8.0"
ring = "0.17.5"
walkdir = "2.4.0"
